common/models/Banner.php
<?php

namespace common\models;

use Yii;

/**
 * This is the model class for table "banner".
 *
 * @property integer $id
 * @property string $name
 * @property string $image
 * @property string $content
 */
class Banner extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'banner';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['content'], 'string'],
            [['name'], 'string', 'max' => 50]
        ];
    }

    /**
     * @return string image hash
     */
    protected function getHash()
    {
        return md5($this->id);
    }

    /**
     * @return string path to image file
     */
    public function getPath()
    {
        return Yii::getAlias('@frontend/web/images/slider/' . $this->getHash() . '.jpg');
    }

    /**
     * @return string URL of the image
     */
    public function getUrl()
    {
        $dir = Yii::getAlias('http://aronex.ru/');
        return $dir.'/images/slider/'.$this->getHash().'.jpg';
    }

    public function afterDelete()
    {
        unlink($this->getPath());
        parent::afterDelete();
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'name' => 'Name',
            'content' => 'Content',
        ];
    }
}

frontend/controllers/CartController.php
<?php

namespace frontend\controllers;

use Yii;
use common\models\Order;
use common\models\OrderItem;
use common\models\Product;
use yz\shoppingcart\ShoppingCart;
use common\models\Edost;
use common\models\Payment;

class CartController extends \yii\web\Controller
{
    public function actionAdd($id)
    {
        $product = Product::findOne($id);
        if ($product) {
            \Yii::$app->cart->put($product);
             return $this->goBack();
        }
    }

    public function actionList()
    {
        $cart = \Yii::$app->cart;
        $products = $cart->getPositions();
        $total = $cart->getCost();

        return $this->render('list', [
           'products' => $products,
           'total' => $total,
        ]);
    }

    public function actionRemove($id)
    {
        $product = Product::findOne($id);
        if ($product) {
            \Yii::$app->cart->remove($product);
            return $this->goBack();
        }
    }

    public function actionUpdate($id, $quantity)
    {
        $product = Product::findOne($id);
        if ($product) {
            \Yii::$app->cart->update($product, $quantity);
            $this->redirect(['/cart/list']);
        }
    }

    public function actionOrderStepOne(){
        if(Yii::$app->session->get('order')){
            $id = Yii::$app->session->get('order');
            $order = Order::findOne($id);
        } else {
            $order = new Order();
        }

        $cart = Yii::$app->cart;
        $products = $cart->getPositions();
        $total = $cart->getCost();

        if ($order->load(Yii::$app->request->post()) && $order->save()) {
            return $this->redirect(['cart/order-step-two']);
        } else {
            return $this->render('step-one', [
                'order' => $order,
            ]);
        }
    }

    public function actionOrderStepOneUr(){
        if(Yii::$app->session->get('order')){
            $id = Yii::$app->session->get('order');
            $order = Order::findOne($id);
        } else {
            $order = new Order();
        }

        $order->scenario = 'one-ur';

        $cart = Yii::$app->cart;
        $products = $cart->getPositions();
        $total = $cart->getCost();

        if ($order->load(Yii::$app->request->post()) && $order->save()) {
            return $this->redirect(['cart/order-step-two-ur']);
        } else {
            return $this->render('step-one-ur', [
                'order' => $order,
            ]);
        }
    }

    public function actionOrderStepTwo(){
        $id = Yii::$app->session->get('order');
        if(!isset($id)){
        	$this->redirect(['cart/order-step-one']);
        }
        $order = Order::findOne($id);
        $order->scenario = 'delevery';

        $cart = Yii::$app->cart;
        $products = $cart->getPositions();
        $total = $cart->getCost();

        if ($order->load(Yii::$app->request->post())){
            $delevery = Order::getDeleveryOne($order->delevery, $order->city);
            $order->delevery_cost = $delevery['price'];
            $order->delevery = $delevery['tarif'];
            $order->save(false);
            return $this->redirect(['cart/order-step-three']);
        } else {
            return $this->render('step-two', [
                'order' => $order,
            ]);
        }
    }

    public function actionOrderStepTwoUr(){
        $id = Yii::$app->session->get('order');
        if(!isset($id)){
        	$this->redirect(['cart/order-step-one']);
        }
        $order = Order::findOne($id);
        $order->scenario = 'delevery';

        $cart = Yii::$app->cart;
        $products = $cart->getPositions();
        $total = $cart->getCost();

        if ($order->load(Yii::$app->request->post())){
            $delevery = Order::getDeleveryOne($order->delevery, $order->city);
            $order->delevery_cost = $delevery['price'];
            $order->delevery = $delevery['tarif'];
            $order->save(false);
            return $this->redirect(['cart/order-step-three-ur']);
        } else {
            return $this->render('step-two', [
                'order' => $order,
            ]);
        }
    }

    public function actionOrderStepThree(){
        $id = Yii::$app->session->get('order');
        if(!isset($id)){
        	$this->redirect(['cart/order-step-one']);
        }
        $order = Order::findOne($id);
        $order->scenario = 'payment';

        $cart = Yii::$app->cart;
        $products = $cart->getPositions();
        $total = $cart->getCost();

        if ($order->load(\Yii::$app->request->post()) && $order->validate()) {
            $transaction = $order->getDb()->beginTransaction();
            $order->save(false);

            foreach($products as $product) {
                $orderItem = new OrderItem();
                $orderItem->order_id = $order->id;
                $orderItem->title = $product->title;
                $orderItem->price = $product->getPrice();
                $orderItem->product_id = $product->id;
                $orderItem->quantity = $product->getQuantity();
                if (!$orderItem->save(false)) {
                    $transaction->rollBack();
                    \Yii::$app->session->addFlash('error', 'Что то пошло не так... Попробуйти связаться с администратором сайта.');
                    return $this->redirect('/cart/list');
                }
            }

            $transaction->commit();
            \Yii::$app->cart->removeAll();
            \Yii::$app->session->remove('order');
            \Yii::$app->session->addFlash('success', 'Спасибо за заказ, мы скоро свяжемяся с вами чтобы обсудить детали заказа.');
            $order->sendEmail();
            return $this->redirect(Payment::pay($order->payment, ($order->delevery_cost + $total) ));
        }

        return $this->render('step-three', [
            'order' => $order,
            'products' => $products,
            'total' => $total,
        ]);
    }

    public function actionOrderStepThreeUr(){
        $id = Yii::$app->session->get('order');
        if(!isset($id)){
        	$this->redirect(['cart/order-step-one']);
        }
        $order = Order::findOne($id);
        $order->scenario = 'payment';

        $cart = Yii::$app->cart;
        $products = $cart->getPositions();
        $total = $cart->getCost();

        if ($order->load(\Yii::$app->request->post()) && $order->validate()) {
            $transaction = $order->getDb()->beginTransaction();
            $order->save(false);

            foreach($products as $product) {
                $orderItem = new OrderItem();
                $orderItem->order_id = $order->id;
                $orderItem->title = $product->title;
                $orderItem->price = $product->getPrice();
                $orderItem->product_id = $product->id;
                $orderItem->quantity = $product->getQuantity();
                if (!$orderItem->save(false)) {
                    $transaction->rollBack();
                    \Yii::$app->session->addFlash('error', 'Что то пошло не так... Попробуйти связаться с администратором сайта.');
                    return $this->redirect('/cart/list');
                }
            }

            $transaction->commit();
            \Yii::$app->cart->removeAll();
            \Yii::$app->session->remove('order');
            \Yii::$app->session->addFlash('success', 'Спасибо за заказ, мы скоро свяжемяся с вами чтобы обсудить детали заказа.');
            $order->sendEmail();
            return $this->redirect(Payment::pay($order->payment, ($order->delevery_cost + $total) ));
        }

        return $this->render('step-three-ur', [
            'order' => $order,
            'products' => $products,
            'total' => $total,
        ]);
    }


    public function actionOrderAccount(){
        $this->layout = 'blank';
        return $this->render('step-account', [
            // 'order' => $order,
        ]);
    }

    public function actionPaymentSuccess($id){
        $this->layout = 'blank';
        $order = Order::findOne($id);
        $order->status = Order::STATUS_PAYMENT;
        $order->save(false);
        var_dump($order->status);
    }
}

frontend/views/cart/list.php
<?php
use \yii\helpers\Html;
use yii\widgets\Breadcrumbs;

/* @var $this yii\web\View */
/* @var $products common\models\Product[] */
$this->params['breadcrumbs'][] = 'Корзина';
$quantity = '';
?>
<section class="section_offset">
    <!-- - - - - - - - - - - - - - Breadcrumbs - - - - - - - - - - - - - - - - -->
    <?= Breadcrumbs::widget([
        'links' => isset($this->params['breadcrumbs']) ? $this->params['breadcrumbs'] : [],
    ]) ?>
    <!-- - - - - - - - - - - - - - End of breadcrumbs - - - - - - - - - - - - - - - - -->
    <h1>Корзина</h1>
    <!-- - - - - - - - - - - - - - Shopping cart table - - - - - - - - - - - - - - - - -->
    <div class="table_wrap">
        <table class="table_type_1 shopping_cart_table">
            <thead>
            <tr>
                <th class="product_image_col"></th>
                <th class="product_title_col">Наименование</th>
                <th>Цена</th>
                <th class="product_qty_col">Количество</th>
                <th>Итого</th>
            </tr>
            </thead>
            <tbody>
            <?php foreach ($products as $product):?>
                <tr>
                    <!-- - - - - - - - - - - - - - Product Image - - - - - - - - - - - - - - - - -->
                    <td class="product_image_col" data-title="Product Image">
                        <a href="/product/view?id=<?=$product->id;?>" class="product_thumb">
                        <?php if(!empty($product->images)): ?>
                            <?= Html::img('/images/product/'.$product->images[0]->url, ['width'=> '83','height'=> '83']);?>
                        <?php else: ?>
                            <img src="/theme/images/shopping_cart_img_3.jpg" alt="">
                        <?php endif; ?>
                        </a>
                    </td>
                    <!-- - - - - - - - - - - - - - End of product Image - - - - - - - - - - - - - - - - -->
                    <!-- - - - - - - - - - - - - - Product name - - - - - - - - - - - - - - - - -->
                    <td data-title="Product Name">
                        <a href="/product/view?id=<?=$product->id;?>" class="product_title"><?= Html::encode($product->title) ?></a>
                    </td>
                    <!-- - - - - - - - - - - - - - End of product name - - - - - - - - - - - - - - - - -->
                    <!-- - - - - - - - - - - - - - Price - - - - - - - - - - - - - - - - -->
                    <td class="subtotal" data-title="Price">
                        <?= $product->price ?> руб.
                    </td>
                    <!-- - - - - - - - - - - - - - End of Price - - - - - - - - - - - - - - - - -->
                    <!-- - - - - - - - - - - - - - Quantity - - - - - - - - - - - - - - - - -->
                    <td data-title="Quantity">
                        <div class="qty min clearfix">

                            <?= Html::a('&#45', ['cart/update', 'id' => $product->getId(), 'quantity' => $quantity - 1], ['class' => 'theme_button', 'disabled' => ($quantity - 1) < 1])?>
                            <input type="text" name="" value="<?= $quantity = $product->getQuantity()?>">
                            <?= Html::a('&#43', ['cart/update', 'id' => $product->getId(), 'quantity' => $quantity + 1], ['class' => 'theme_button'])?>

                        </div><!--/ .qty.min.clearfix-->
                    </td>
                    <!-- - - - - - - - - - - - - - End of quantity - - - - - - - - - - - - - - - - -->
                    <!-- - - - - - - - - - - - - - Total - - - - - - - - - - - - - - - - -->
                    <td class="total" data-title="Total">
                        <?= $product->getCost() ?> руб.
                    </td>
                    <!-- - - - - - - - - - - - - - End of total - - - - - - - - - - - - - - - - -->
                </tr>
            <?php endforeach ?>

            </tbody>
        </table>
    </div><!--/ .table_wrap -->

    <footer class="bottom_box on_the_sides">
        <div class="right_side">
            <?= Html::a('Оформить заказ', ['cart/order-step-one'], ['class' => 'button_blue middle_btn'])?>
        </div>
    </footer><!--/ .bottom_box -->
    <!-- - - - - - - - - - - - - - End of shopping cart table - - - - - - - - - - - - - - - - -->
</section><!--/ .section_offset -->
<section class="col-sm-4" style="float:right">
    <h3>Итого</h3>
    <div class="table_wrap">
        <table class="zebra">
            <tfoot>

            <tr class="total">
                <td>К оплате</td>
                <td><?= $total ?> руб.</td>
            </tr>
            </tfoot>
        </table>
    </div>
    <footer class="bottom_box">
        <?= Html::a('Оформить заказ', ['cart/order-step-one'], ['class' => 'button_blue middle_btn'])?>

    </footer>
</section><!-- / [col] -->


frontend/views/cart/step-account.php
<!DOCTYPE html>
<head>
<meta charset=utf-8>
<title>Квитанция "Сбербанка"</title>
<style type="text/css">
  table.sbb td { color: #000000; font-size: 12px; font-family: Times New Roman, Arial, Tahoma; }
  @media print {
    input {display: none; }
  }
</style>
</head>
<body>
<table style="width: 180mm; height: 145mm;" class="sbb" border="0" cellpadding="0" cellspacing="0">
    <tbody>
        <tr valign="top">
            <td style="border-right: medium none; border-width: 1pt medium medium 1pt; border-style: solid none none solid; border-color: rgb(0, 0, 0) -moz-use-text-color -moz-use-text-color rgb(0, 0, 0); width: 50mm; height: 70mm;" align="center"><strong>Извещение</strong><br><font style="FONT-SIZE: 53mm">&nbsp;<br></font><strong>Кассир</strong></td>
            <td style="border-right: 1pt solid rgb(0, 0, 0); border-width: 1pt 1pt medium; border-style: solid solid none; border-color: rgb(0, 0, 0) rgb(0, 0, 0) -moz-use-text-color;" align="center">
            <table style="margin-top: 3pt; width: 122mm;" border="0" cellpadding="0" cellspacing="0">

                <tbody>
                    <tr>
                        <td align="right"><small><em>Форма № ПД-4</em></small></td>
                    </tr>
                    <tr>
                        <td style="border-bottom: 1pt solid rgb(0, 0, 0); font-size:10px;"><p><strong>ООО "Репорт-Информ"<br/> </strong></p></td>
                    </tr>

                    <tr>
                        <td align="center"><small>(наименование получателя платежа)</small></td>
                    </tr>
                </tbody>
            </table>
            <table style="margin-top: 3pt; width: 122mm;" border="0" cellpadding="0" cellspacing="0">
                <tbody>
                    <tr>

                        <td style="width: 37mm; border-bottom: 1pt solid rgb(0, 0, 0);">7705754850</td>
                        <td style="width: 9mm;">&nbsp;</td>
                        <td style="border-bottom: 1pt solid rgb(0, 0, 0);">40702810138170109386</td>
                    </tr>
                    <tr>
                        <td align="center"><small>(ИНН получателя платежа)</small></td>
                        <td><small>&nbsp;</small></td>

                        <td align="center"><small>(номер счета получателя платежа)</small></td>
                    </tr>
                </tbody>
            </table>
            <table style="margin-top: 3pt; width: 122mm;" border="0" cellpadding="0" cellspacing="0">
                <tbody>
                    <tr>
                        <td>в&nbsp;</td>

                        <td style="width: 73mm; border-bottom: 1pt solid rgb(0, 0, 0);">ОАО "СБЕРБАНК РОССИИ",г.МОСКВА</td>
                        <td align="right">БИК&nbsp;&nbsp;</td>
                        <td style="width: 33mm; border-bottom: 1pt solid rgb(0, 0, 0);">044525225</td>
                    </tr>
                    <tr>
                        <td>&nbsp;</td>

                        <td align="center"><small>(наименование банка получателя платежа)</small></td>
                        <td>&nbsp;</td>
                        <td>&nbsp;</td>
                    </tr>
                </tbody>
            </table>
            <table style="margin-top: 3pt; width: 122mm;" border="0" cellpadding="0" cellspacing="0">
                <tbody>

                    <tr>
                        <td nowrap="nowrap" width="1%">Номер кор./сч. банка получателя платежа&nbsp;&nbsp;</td>
                        <td style="border-bottom: 1pt solid rgb(0, 0, 0);" width="100%">30101810400000000225</td>
                    </tr>
                </tbody>
            </table>
            <table style="margin-top: 3pt; width: 122mm;" border="0" cellpadding="0" cellspacing="0">
                <tbody>

                    <tr>
                        <td style="width: 60mm; border-bottom: 1pt solid rgb(0, 0, 0);">Оплата за услуги</td>
                        <td style="width: 2mm;">&nbsp;</td>
                        <td style="border-bottom: 1pt solid rgb(0, 0, 0);">&nbsp;</td>
                    </tr>
                    <tr>
                        <td align="center"><small>(наименование платежа)</small></td>
                        <td><small>&nbsp;</small></td>

                        <td align="center"><small>(номер лицевого счета (код) плательщика)</small></td>
                    </tr>
                </tbody>
            </table>
            <table style="margin-top: 3pt; width: 122mm;" border="0" cellpadding="0" cellspacing="0">
                <tbody>
                    <tr>
                        <td nowrap="nowrap" width="1%">Ф.И.О. плательщика&nbsp;&nbsp;</td>

                        <td style="border-bottom: 1pt solid rgb(0, 0, 0);" width="100%">&nbsp;</td>
                    </tr>
                </tbody>
            </table>
            <table style="margin-top: 3pt; width: 122mm;" border="0" cellpadding="0" cellspacing="0">
                <tbody>
                    <tr>
                        <td nowrap="nowrap" width="1%">Адрес плательщика&nbsp;&nbsp;</td>

                        <td style="border-bottom: 1pt solid rgb(0, 0, 0);" width="100%">&nbsp;</td>
                    </tr>
                </tbody>
            </table>
            <table style="margin-top: 3pt; width: 122mm;" border="0" cellpadding="0" cellspacing="0">
                <tbody>
                    <tr>
                        <td>Сумма платежа&nbsp;<font>&nbsp;_____&nbsp;</font>&nbsp;руб.&nbsp;____ коп.</td>

                        <td align="right">&nbsp;&nbsp;Сумма платы за услуги&nbsp;&nbsp;_____&nbsp;руб.&nbsp;____&nbsp;коп.</td>
                    </tr>
                </tbody>
            </table>
            <table style="margin-top: 3pt; width: 122mm;" border="0" cellpadding="0" cellspacing="0">
                <tbody>

                    <tr>
                        <td>Итого&nbsp;&nbsp;_______&nbsp;руб.&nbsp;____&nbsp;коп.</td>
                        <td align="right">&nbsp;&nbsp;«______»________________ 201____ г.</td>
                    </tr>
                </tbody>

            </table>
            <table style="margin-top: 3pt; width: 122mm;" border="0" cellpadding="0" cellspacing="0">
                <tbody>
                    <tr>
                        <td><small>С условиями приема указанной в 
платежном документе суммы, в т.ч. с суммой взимаемой платы за услуги 
банка, ознакомлен и согласен.</small></td>
                    </tr>
                </tbody>
            </table>

            <table style="margin-top: 3pt; width: 122mm;" border="0" cellpadding="0" cellspacing="0">
                <tbody>
                    <tr>
                        <td align="right"><strong>Подпись плательщика _____________________</strong></td>
                    </tr>
                </tbody>
            </table>
            </td>

        </tr>
        <tr valign="top">
            <td style="border-right: medium none; border-width: 1pt medium 1pt 1pt; border-style: solid none solid solid; border-color: rgb(0, 0, 0) -moz-use-text-color rgb(0, 0, 0) rgb(0, 0, 0); width: 50mm; height: 70mm;" align="center"><font style="FONT-SIZE: 50mm">&nbsp;<br></font><strong>Квитанция</strong><br><font style="FONT-SIZE: 8pt">&nbsp;<br></font><strong>Кассир</strong></td>
            <td style="border-right: 1pt solid rgb(0, 0, 0); border-width: 1pt; border-style: solid; border-color: rgb(0, 0, 0);" align="center">
            <table style="margin-top: 3pt; width: 122mm;" border="0" cellpadding="0" cellspacing="0">

                <tbody>
                    <tr>
                        <td align="right"><small><em>Форма № ПД-4</em></small></td>
                    </tr>
                    <tr>
                        <td style="border-bottom: 1pt solid rgb(0, 0, 0); font-size:10px;"><p><strong>ООО "Репорт-Информ"</strong></p></td>
                    </tr>

                    <tr>
                        <td align="center"><small>(наименование получателя платежа)</small></td>
                    </tr>
                </tbody>
            </table>
            <table style="margin-top: 3pt; width: 122mm;" border="0" cellpadding="0" cellspacing="0">
                <tbody>
                    <tr>

                        <td style="width: 37mm; border-bottom: 1pt solid rgb(0, 0, 0);">7705754850</td>
                        <td style="width: 9mm;">&nbsp;</td>
                        <td style="border-bottom: 1pt solid rgb(0, 0, 0);">40702810138170109386</td>
                    </tr>
                    <tr>
                        <td align="center"><small>(ИНН получателя платежа)</small></td>
                        <td><small>&nbsp;</small></td>

                        <td align="center"><small>(номер счета получателя платежа)</small></td>
                    </tr>
                </tbody>
            </table>
            <table style="margin-top: 3pt; width: 122mm;" border="0" cellpadding="0" cellspacing="0">
                <tbody>
                    <tr>
                        <td>в&nbsp;</td>

                        <td style="width: 73mm; border-bottom: 1pt solid rgb(0, 0, 0);">ОАО "СБЕРБАНК РОССИИ",г.МОСКВА</td>
                        <td align="right">БИК&nbsp;&nbsp;</td>
                        <td style="width: 33mm; border-bottom: 1pt solid rgb(0, 0, 0);">044525225</td>
                    </tr>
                    <tr>
                        <td>&nbsp;</td>

                        <td align="center"><small>(наименование банка получателя платежа)</small></td>
                        <td>&nbsp;</td>
                        <td>&nbsp;</td>
                    </tr>
                </tbody>
            </table>
            <table style="margin-top: 3pt; width: 122mm;" border="0" cellpadding="0" cellspacing="0">
                <tbody>

                    <tr>
                        <td nowrap="nowrap" width="1%">Номер кор./сч. банка получателя платежа&nbsp;&nbsp;</td>
                        <td style="border-bottom: 1pt solid rgb(0, 0, 0);" width="100%">30101810400000000225</td>
                    </tr>
                </tbody>
            </table>
            <table style="margin-top: 3pt; width: 122mm;" border="0" cellpadding="0" cellspacing="0">
                <tbody>

                    <tr>
                        <td style="width: 60mm; border-bottom: 1pt solid rgb(0, 0, 0);">Оплата за услуги</td>
                        <td style="width: 2mm;">&nbsp;</td>
                        <td style="border-bottom: 1pt solid rgb(0, 0, 0);">&nbsp;</td>
                    </tr>
                    <tr>
                        <td align="center"><small>(наименование платежа)</small></td>
                        <td><small>&nbsp;</small></td>

                        <td align="center"><small>(номер лицевого счета (код) плательщика)</small></td>
                    </tr>
                </tbody>
            </table>
            <table style="margin-top: 3pt; width: 122mm;" border="0" cellpadding="0" cellspacing="0">
                <tbody>
                    <tr>
                        <td nowrap="nowrap" width="1%">Ф.И.О. плательщика&nbsp;&nbsp;</td>

                        <td style="border-bottom: 1pt solid rgb(0, 0, 0);" width="100%">&nbsp;</td>
                    </tr>
                </tbody>
            </table>
            <table style="margin-top: 3pt; width: 122mm;" border="0" cellpadding="0" cellspacing="0">
                <tbody>
                    <tr>
                        <td nowrap="nowrap" width="1%">Адрес плательщика&nbsp;&nbsp;</td>

                        <td style="border-bottom: 1pt solid rgb(0, 0, 0);" width="100%">&nbsp;</td>
                    </tr>
                </tbody>
            </table>
            <table style="margin-top: 3pt; width: 122mm;" border="0" cellpadding="0" cellspacing="0">
                <tbody>
                    <tr>
                        <td>Сумма платежа&nbsp;<font>&nbsp;_____&nbsp;</font>&nbsp;руб.&nbsp;____ коп.</td>

                        <td align="right">&nbsp;&nbsp;Сумма платы за услуги&nbsp;&nbsp;_____&nbsp;руб.&nbsp;____&nbsp;коп.</td>
                    </tr>
                </tbody>
            </table>
            <table style="margin-top: 3pt; width: 122mm;" border="0" cellpadding="0" cellspacing="0">
                <tbody>

                    <tr>
                        <td>Итого&nbsp;&nbsp;_______&nbsp;руб.&nbsp;____&nbsp;коп.</td>
                        <td align="right">&nbsp;&nbsp;«______»________________ 201____ г.</td>
                    </tr>
                </tbody>

            </table>
            <table style="margin-top: 3pt; width: 122mm;" border="0" cellpadding="0" cellspacing="0">
                <tbody>
                    <tr>
                        <td><small>С условиями приема указанной в 
платежном документе суммы, в т.ч. с суммой взимаемой платы за услуги 
банка, ознакомлен и согласен.</small></td>
                    </tr>
                </tbody>
            </table>

            <table style="margin-top: 3pt; width: 122mm;" border="0" cellpadding="0" cellspacing="0">
                <tbody>
                    <tr>
                        <td align="right"><strong>Подпись плательщика _____________________</strong></td>
                    </tr>
                </tbody>
            </table>
            </td>
        </tr>
    </tbody>
</table>
<br><input value=" &nbsp; Печать &nbsp; " onClick="print(document);" type="button"><br>
</body></html>

frontend/views/cart/step-two.php
<?php
use \yii\helpers\Html;
use \yii\widgets\ActiveForm;
use yii\widgets\Breadcrumbs;
use common\models\Order;

$this->title = 'Оформление заказа Шаг 2';
$this->params['breadcrumbs'][] = $this->title;
?>
<section class="section_offset">
    <!-- - - - - - - - - - - - - - Breadcrumbs - - - - - - - - - - - - - - - - -->
    <?= Breadcrumbs::widget([
        'links' => isset($this->params['breadcrumbs']) ? $this->params['breadcrumbs'] : [],
    ]) ?>
    <!-- - - - - - - - - - - - - - End of breadcrumbs - - - - - - - - - - - - - - - - -->
</section>

<!-- - - - - - - - - - - - - - Order review - - - - - - - - - - - - - - - - -->
<?php
$form = ActiveForm::begin([
    'id' => 'order-form',
    'class' => 'type_2',
]) ?>

<!-- - - - - - - - - - - - - - Shipping method - - - - - - - - - - - - - - - - -->

<section class="section_offset" id="delevery">
    <h3>Способ доставки</h3>
    <div class="theme_box">
        <p class="subcaption"><b>Стоимость доставки до: <?= $order->region .' '. $order->city .' '. $order->street  .' '.  $order->house .' - '. $order->apartment; ?></b></p>
        <?php $delevery = Order::getDelevery($order->city);
            if($delevery != false){
               echo $form->field($order, 'delevery')->radioList($delevery,
                   [
                       'item' => function($index, $label, $name, $checked, $value) {
                           $return  = '<label class="modal-radio">';
                           $return .= '<input type="radio" name="' . $name . '" value="' . $value . '" tabindex="3">';
                           $return .= '<span>' .  $label . '</span>';
                           $return .= '</label>';
                           return $return;
                       }
                   ]
               ) ->label(false);;
            } else {
                echo '<b class="required">Не корректно введен город</b>
                      <p>Для того чтобы расчитать стоимость доставки, необходимо ввести корректное название города доставки<br>
                      Если у вас возникли проблемы с этим, пожалуйста обратитесь в онлайн чат поддержки сайта</p>';
            }
        ?>
    </div>
     <footer class="bottom_box on_the_sides">
         <div class="left_side">
            <a href="/cart/order-step-one" class="button_blue middle_btn">Вернуться</a>
        </div>
        <div class="right_side">
            <?= Html::submitButton('Следующий Шаг', ['class' => 'button_blue middle_btn']) ?>
        </div>
    </footer>
</section>
<!-- - - - - - - - - - - - - - End of shipping method - - - - - - - - - - - - - - - - -->

<?php ActiveForm::end() ?>